/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashadvance_multicompany;

import static cashadvance_multicompany.CashAdvanRequest.cmbSupplierADV;
import static cashadvance_multicompany.CashAdvanRequest.cmb_IT1GP;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

//import static cashadvance_multicompany.frmWHTAX.rdo1per;
//import static cashadvance_multicompany.frmWHTAX.rdo2per;
//import static cashadvance_multicompany.frmWHTAX.rdo3per;
//import static cashadvance_multicompany.frmWHTAX.rdo5per;
//import static cashadvance_multicompany.frmWHTAX.rdoPTC;
//import static cashadvance_multicompany.frmWHTAX.rdoReturnKBANK;
//import static cashadvance_multicompany.frmWHTAX.rdoReturnSCB;
//import static cashadvance_multicompany.frmWHTAX.rdoTransBank;
import static cashadvance_multicompany.frmWHTAX.txtAdvanceNo1;
//import static cashadvance_multicompany.frmWHTAX.txtBBranch;
//import static cashadvance_multicompany.frmWHTAX.txtBName;
//import static cashadvance_multicompany.frmWHTAX.txtBNumber;

import static cashadvance_multicompany.CashAdvanRequest.txtaccname;
import static cashadvance_multicompany.CashAdvanRequest.txtaccno;
import static cashadvance_multicompany.frmWHTAX.txtamount1;
import static cashadvance_multicompany.frmWHTAX.txtamt1;
import static cashadvance_multicompany.frmWHTAX.txtamtbfvat1;
import static cashadvance_multicompany.CashAdvanRequest.txtbranch;
//import static cashadvance_multicompany.frmWHTAX.txtrefund1;
//import static cashadvance_multicompany.frmWHTAX.txtreturn1;
import static cashadvance_multicompany.frmWHTAX.txtvat1;

import static cashadvance_multicompany.frmLogin.LoginCono;
import static cashadvance_multicompany.frmLogin.LoginDivision;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static cashadvance_multicompany.frmWHTAX.txtbalance;
import static cashadvance_multicompany.frmWHTAX.griddetail;

/**
 *
 * @author Monthon
 */
public class frmAddLineInvUser extends javax.swing.JFrame {

    public static DefaultTableModel model;
    public static String ProgramStep = "";

    /**
     * Creates new form frmsearch
     */
    public frmAddLineInvUser() {
        initComponents();
        this.setTitle("Cash Advance Request : Add Invoice");
        SETT_BRAC.setVisible(false);
        GetExpenseGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdSGEXP = new javax.swing.JComboBox<>();
        cmdHGEXP = new javax.swing.JComboBox<>();
        cmdI3desc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sharesv = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtdescline = new javax.swing.JTextField();
        txtinvoiceline = new javax.swing.JTextField();
        dateInvoiceline = new org.jdesktop.swingx.JXDatePicker();
        txtvatcline = new javax.swing.JTextField();
        txtsupline = new javax.swing.JTextField();
        txtcostline = new javax.swing.JTextField();
        txtamtline = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        SETT_BRAC = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnSearchSupp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        cmdSGEXP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmdSGEXP.setEnabled(false);
        cmdSGEXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSGEXPActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSGEXP);
        cmdSGEXP.setBounds(90, 180, 530, 30);

        cmdHGEXP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmdHGEXP.setEnabled(false);
        cmdHGEXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHGEXPActionPerformed(evt);
            }
        });
        getContentPane().add(cmdHGEXP);
        cmdHGEXP.setBounds(90, 140, 530, 30);

        cmdI3desc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmdI3desc.setEnabled(false);
        cmdI3desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdI3descActionPerformed(evt);
            }
        });
        getContentPane().add(cmdI3desc);
        cmdI3desc.setBounds(90, 220, 530, 30);

        jLabel1.setText("Sub Group :");
        jLabel1.setEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 180, 70, 30);

        jLabel2.setText("Group Desc :");
        jLabel2.setEnabled(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 220, 80, 30);

        jLabel3.setText("Group :");
        jLabel3.setEnabled(false);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 50, 30);

        sharesv.setText("Share Service");
        sharesv.setEnabled(false);
        getContentPane().add(sharesv);
        sharesv.setBounds(90, 250, 140, 40);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 290, 130, 30);

        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText("Vat%");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(630, 10, 70, 20);

        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("INVOICE");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(10, 10, 50, 16);

        jLabel25.setForeground(new java.awt.Color(255, 0, 51));
        jLabel25.setText("Name");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(300, 70, 50, 16);

        jLabel26.setForeground(new java.awt.Color(255, 0, 51));
        jLabel26.setText("Invoice Date");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(140, 10, 80, 16);

        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("Cost Center");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(10, 70, 80, 20);

        jLabel29.setForeground(new java.awt.Color(255, 0, 51));
        jLabel29.setText("Amt");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(520, 10, 100, 20);

        txtdescline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtdescline);
        txtdescline.setBounds(300, 30, 210, 30);

        txtinvoiceline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtinvoiceline);
        txtinvoiceline.setBounds(10, 30, 120, 30);

        dateInvoiceline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(dateInvoiceline);
        dateInvoiceline.setBounds(140, 30, 150, 30);

        txtvatcline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtvatcline);
        txtvatcline.setBounds(630, 30, 70, 30);

        txtsupline.setEditable(false);
        txtsupline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtsupline);
        txtsupline.setBounds(140, 90, 150, 30);

        txtcostline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtcostline);
        txtcostline.setBounds(10, 90, 120, 30);

        txtamtline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtamtline);
        txtamtline.setBounds(520, 30, 100, 30);

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtname);
        txtname.setBounds(300, 90, 210, 30);

        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("Supplier");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(140, 70, 100, 16);
        getContentPane().add(SETT_BRAC);
        SETT_BRAC.setBounds(630, 90, 69, 30);

        jLabel33.setForeground(new java.awt.Color(255, 0, 51));
        jLabel33.setText("Description");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(300, 10, 210, 16);

        btnSearchSupp.setText("Search");
        btnSearchSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSuppActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchSupp);
        btnSearchSupp.setBounds(520, 90, 100, 30);

        setSize(new java.awt.Dimension(728, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdHGEXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHGEXPActionPerformed
        try {
            String Nosub = (String) cmdHGEXP.getSelectedItem();
            if (!Nosub.equalsIgnoreCase("null") && !Nosub.equalsIgnoreCase("")) {
                String[] SubGroup = Nosub.split(":");
                GetExpenseSubGroup(SubGroup[0].trim());

            } else {
                System.err.println("");
            }
        } catch (Exception e) {
            System.err.println("");
        }

    }//GEN-LAST:event_cmdHGEXPActionPerformed

    private void cmdSGEXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSGEXPActionPerformed
        try {
            String Nosub = (String) cmdSGEXP.getSelectedItem();
            if (!Nosub.equalsIgnoreCase("null") && !Nosub.equalsIgnoreCase("")) {
                String[] SubGroup = Nosub.split(":");
                GetExpenseSubGroupDesc(SubGroup[0].trim());

            } else {
                System.err.println("");
            }
        } catch (Exception e) {
            System.err.println("");
        }
    }//GEN-LAST:event_cmdSGEXPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            if (txtinvoiceline.getText().length() >= 16) {
                msbox("INVOICE maxximum 15");
                return;
            }
            if (txtdescline.getText().length() >= 61) {
                msbox("Description maxximum 60");
                return;
            }

            if (txtvatcline.getText().length() >= 2) {
                msbox("Vat maxximum 1");
                return;
            }

            ClassCheckDataProgram cdp = new ClassCheckDataProgram();
            double amtqty = 0;
            model = (DefaultTableModel) griddetail.getModel();
            String EPRH_RQSDT = cdp.GetDateFormatSet(dateInvoiceline.getDate());

            double amt = 0;
            try {
                amt = cdp.Double2digitReturn(Double.parseDouble(txtamtline.getText()));
            } catch (Exception e) {
                amt = 0;
            }

            double vatc = 0;
            try {
                vatc = cdp.Double2digitReturn(Double.parseDouble(txtvatcline.getText()));
            } catch (Exception e) {
                vatc = 0;
            }

            double vatamt = cdp.Double2digitReturn((amt * vatc) / 100);
            // double vatamt=Classcheck.Double2digitReturn((double)(model.getValueAt(i, 7)));// BANK EDIT FOR RACHANEEWAN
            double totalamt = cdp.Double2digitReturn(amt + vatamt);

            String costcentergrid = txtcostline.getText().trim().toUpperCase();

            Classgetdata cgd = new Classgetdata();

//            String GroupDesc = (String) cmdI3desc.getSelectedItem();
//            String[] NoDesc = GroupDesc.split(":");
            String NoDesc = "1.1";
            SETT_BRAC.setText("");
//            if (sharesv.isSelected()) {
//                SETT_BRAC.setText("2");
//            } else {
            SETT_BRAC.setText("1");
//            }
            String BranchAcc = SETT_BRAC.getText().trim();

            if (!costcentergrid.equals("")) {
                int countcost = cgd.GetCostcenterWithCodeData(costcentergrid);
                if (countcost == 0) {
                    msbox("Costcenter Not Found");
                    return;
                } else {
                    ClassSetdata cds = new ClassSetdata();
                    cds.InsertLine(LoginCono, LoginDivision, NoDesc.trim(), BranchAcc, txtAdvanceNo1.getText().trim(), txtinvoiceline.getText().trim(), txtsupline.getText(), EPRH_RQSDT,
                            txtdescline.getText(), txtcostline.getText().toUpperCase(), txtamtline.getText(), txtvatcline.getText(),
                            String.valueOf(vatamt), String.valueOf(totalamt), "10",false
                    );

                    Get_DetailGrid(txtAdvanceNo1.getText().trim());
                }
            }

            dispose();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Get_DetailGrid(String CashAdvanceNo) {

        Classgetdata cgd = new Classgetdata();
        ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();
        ResultSet rs = cgd.GetDataAdvanceDetailResultData(CashAdvanceNo);
        try {
            //    SetModel();
            model = (DefaultTableModel) griddetail.getModel();
            int iiii = 0;
//         
            Double amt = 0.00;
            Double vat = 0.00;
            Double amtBeforeVat = 0.00;
            Double Sum = 0.00;
            Double Advamt = Double.parseDouble(txtamount1.getText().trim());
            while (rs.next()) {
                //  String Nassme= cgd.GetItemName_MitMas(rs.getString("EPRL_ITNO").trim());
                model.setValueAt(rs.getString("SETT_INVC").trim(), iiii, 0);
                model.setValueAt(rs.getString("SETT_SUPP").trim(), iiii, 1);
                model.setValueAt(cgd.Get_SupplierNameWithCode2(rs.getString("SETT_SUPP").trim()), iiii, 2);
                model.setValueAt(checkdataprogram.GetDateFormatSetShowString(checkdataprogram.GetDecmalTodate(rs.getInt("SETT_INVD"))), iiii, 3);

                model.setValueAt(rs.getString("SETT_DESC").trim(), iiii, 4);
                model.setValueAt(rs.getString("SETT_COST").trim(), iiii, 5);

                model.setValueAt(rs.getDouble("SETT_AMTB"), iiii, 6);
                model.setValueAt(rs.getDouble("SETT_VATC"), iiii, 7);
                model.setValueAt(rs.getDouble("SETT_VATA"), iiii, 8);
                model.setValueAt(rs.getString("SETT_NODES"), iiii, 9);
                model.setValueAt(rs.getDouble("SETT_AMTT"), iiii, 10);
                model.setValueAt(rs.getString("SETT_BRAC"), iiii, 11);
                amt += rs.getDouble("SETT_AMTT");
                vat += rs.getDouble("SETT_VATA");
                amtBeforeVat += rs.getDouble("SETT_AMTB");
                iiii++;

            }
            amtBeforeVat = checkdataprogram.Double2digitReturn(amtBeforeVat);
            amt = checkdataprogram.Double2digitReturn(amt);
            vat = checkdataprogram.Double2digitReturn(vat);
            txtvat1.setText(String.valueOf(vat));
            txtamtbfvat1.setText(String.valueOf(amtBeforeVat));
            txtamt1.setText(String.valueOf(amtBeforeVat + vat));
//            
            Cal_AmountSettlementWithGrid(Advamt, amtBeforeVat, vat, amt);

            rs.close();

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

//    private void Cal_WHTAX() {
//        Double AdvAmt = Double.parseDouble(txtamtbfvat1.getText().trim());
//        if (rdo1per.isSelected()) {
//            AdvAmt = (AdvAmt * 1) / 100;
//            txtwhtax1.setText(String.valueOf(AdvAmt));
//        } else if (rdo2per.isSelected()) {
//            AdvAmt = (AdvAmt * 2) / 100;
//            txtwhtax1.setText(String.valueOf(AdvAmt));
//        } else if (rdo3per.isSelected()) {
//            AdvAmt = (AdvAmt * 3) / 100;
//            txtwhtax1.setText(String.valueOf(AdvAmt));
//        } else if (rdo5per.isSelected()) {
//            AdvAmt = (AdvAmt * 5) / 100;
//            txtwhtax1.setText(String.valueOf(AdvAmt));
//        } else {
//            AdvAmt = (AdvAmt * 0) / 100;
//            txtwhtax1.setText(String.valueOf(AdvAmt));
//        }
//    }
//    private void Set_RdoSettlement(boolean Status) {
//        rdoReturnSCB.setEnabled(Status);
//        rdoReturnKBANK.setEnabled(Status);
//        rdoPTC.setEnabled(Status);
//        rdoTransBank.setEnabled(Status);
//        rdoPTC.setSelected(Status);
//        rdoReturnSCB.setSelected(Status);
//        rdoReturnKBANK.setSelected(Status);
//        rdoPTC.setSelected(Status);
//        rdoTransBank.setSelected(Status);
//
//    }
//    private void ClearBanktxt() {
//        txtBNumber.setText("");
//        txtBBranch.setText("");
//        txtBName.setText("");
//    }
    private void Cal_AmountSettlementWithGrid(Double Advamt, Double AmtBfVat, Double AmtVat, Double TotalAmt) {
        ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();

        Double Sum = 0.00;
        Sum = Advamt - (AmtBfVat + AmtVat);
        Sum = checkdataprogram.Double2digitReturn(Sum);
        System.out.println(Sum);
        txtbalance.setText(String.valueOf(Sum));

    }
    private void btnSearchSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSuppActionPerformed
        frmsearch.ProgramStep = "cashadvstepWHTAX";
        new frmsearch().setVisible(true);
    }//GEN-LAST:event_btnSearchSuppActionPerformed

    private void cmdI3descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdI3descActionPerformed
        try {
            Classgetdata cgd = new Classgetdata();
            sharesv.setEnabled(true);
            sharesv.setSelected(false);
            String I3DS_I3AIT1 = "", I3DS_I3AIT2 = "";
            String NoDesc = (String) cmdI3desc.getSelectedItem();
            if (!NoDesc.equalsIgnoreCase("null") && !NoDesc.equalsIgnoreCase("") && !NoDesc.equalsIgnoreCase("Please Select Sub Group")) {
                String[] SubGroup = NoDesc.split(":");
                ResultSet rsl = cgd.Check_BranchAC(SubGroup[0]);
                while (rsl.next()) {
                    I3DS_I3AIT1 = rsl.getString("I3DS_I3AIT1").trim();
                    I3DS_I3AIT2 = rsl.getString("I3DS_I3AIT2").trim();
                }
                if (I3DS_I3AIT1.equals("-")) {
                    sharesv.setSelected(true);
                    sharesv.setEnabled(false);
                    System.out.println("I3DS_I3AIT1 = " + I3DS_I3AIT1);
                } else if (I3DS_I3AIT2.equals("-")) {
                    sharesv.setSelected(false);
                    sharesv.setEnabled(false);
                    System.out.println("I3DS_I3AIT2 = " + I3DS_I3AIT2);
                }

            }
        } catch (Exception e) {
            System.err.println("");
        }

    }//GEN-LAST:event_cmdI3descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddLineInvUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddLineInvUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddLineInvUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddLineInvUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddLineInvUser().setVisible(true);
            }
        });
    }

    private void msbox(String strr) {
        int dialogButton = JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(null, strr, "Warning", dialogButton);
    }

    public void GetExpenseGroup() {

        cmdHGEXP.removeAllItems();
        try {
            Classgetdata cgr = new Classgetdata();
            String[] NoGroup = cmb_IT1GP.getText().split(":");
            ResultSet rs1 = cgr.GetExpensHeadGroupWithNo(NoGroup[0]);
            cmdHGEXP.addItem("Please Select Group");
            while (rs1.next()) {
                cmdHGEXP.addItem(rs1.getString("I1GP_NOGP").trim() + " : " + rs1.getString("I1GP_DESGP").trim());
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAddLineInvUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void GetExpenseSubGroup(String NoSub) {

        cmdSGEXP.removeAllItems();
        try {
            Classgetdata cgr = new Classgetdata();
            ResultSet rs1 = cgr.GetExpensSubGroup(NoSub);
            cmdSGEXP.addItem("Please Select Sub Group");
            while (rs1.next()) {
                cmdSGEXP.addItem(rs1.getString("I2SG_NOSG").trim() + " : " + rs1.getString("I2SG_DESSG").trim());
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAddLineInvUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void GetExpenseSubGroupDesc(String NoSub) {

        cmdI3desc.removeAllItems();
        try {
            Classgetdata cgr = new Classgetdata();
            ResultSet rs1 = cgr.GetExpensSubGroupDesc(NoSub);
            cmdI3desc.addItem("Please Select Sub Group");
            while (rs1.next()) {
                cmdI3desc.addItem(rs1.getString("I3DS_NODES").trim() + " : " + rs1.getString("I3DS_DESC").trim());
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAddLineInvUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField SETT_BRAC;
    private javax.swing.JButton btnSearchSupp;
    public static javax.swing.JComboBox<String> cmdHGEXP;
    public static javax.swing.JComboBox<String> cmdI3desc;
    public static javax.swing.JComboBox<String> cmdSGEXP;
    private org.jdesktop.swingx.JXDatePicker dateInvoiceline;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    public static javax.swing.JCheckBox sharesv;
    private javax.swing.JTextField txtamtline;
    private javax.swing.JTextField txtcostline;
    private javax.swing.JTextField txtdescline;
    private javax.swing.JTextField txtinvoiceline;
    public static javax.swing.JTextField txtname;
    public static javax.swing.JTextField txtsupline;
    private javax.swing.JTextField txtvatcline;
    // End of variables declaration//GEN-END:variables
}
