/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashadvance_multicompany;

import static cashadvance_multicompany.ConnectDB2.ErrorLogs;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author aticha
 */
public class frmLogin extends javax.swing.JFrame {

    public static String LoginUsername;
    public static String LoginPassword;
    public static String LoginCono;
    public static String LoginDivision;

    public static String LoginCompanyName;
    public static DefaultComboBoxModel ListCompany;
    public static ResultSet rsCompany;
    public static ResultSet rsFacility;
    public static String UserM3;
    public static String PasswordM3;

    public static String LoginUrlConnectionM3;
    public static String LoginAppServer;
    public static int LoginAppPort;

    public static String Table_fin_caadd;
    public static String Table_fin_sead;
    public static String Table_fin_cact;
    public static String dbname;
    public static String dbM3Name;

    /**
     * Creates new form LoginMain
     */
    public frmLogin() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("icon.png"));

        this.setTitle("Login For BR GROUP");
        lblCompanyName.setText("BR GROUP");
        try {

            GetCompanyResultData();  //metthod company
//            GetFacResultData();     //metthod Facility

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        txtUsername = new java.awt.TextField();
        btncancel = new java.awt.Button();
        btnlogin = new java.awt.Button();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblCompanyName = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        CmbCompany = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("User Name");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });
        label1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                label1ComponentHidden(evt);
            }
        });
        getContentPane().add(label1);
        label1.setBounds(20, 70, 80, 23);

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("Password");
        getContentPane().add(label2);
        label2.setBounds(30, 130, 70, 23);

        txtUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(110, 70, 230, 30);

        btncancel.setBackground(new java.awt.Color(255, 204, 204));
        btncancel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btncancel.setLabel("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(260, 250, 90, 38);

        btnlogin.setBackground(new java.awt.Color(204, 255, 255));
        btnlogin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnlogin.setLabel("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(100, 250, 90, 38);

        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordField1.setToolTipText("");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(110, 130, 230, 30);

        lblCompanyName.setAlignment(java.awt.Label.CENTER);
        lblCompanyName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(lblCompanyName);
        lblCompanyName.setBounds(100, 20, 270, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Company");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 60, 30);

        CmbCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCompanyActionPerformed(evt);
            }
        });
        getContentPane().add(CmbCompany);
        CmbCompany.setBounds(110, 190, 230, 30);

        jButton1.setText("คู่มือ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 70, 73, 28);

        setSize(new java.awt.Dimension(444, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        Connection conn;
        try {
            LoginUsername = txtUsername.getText().trim().toUpperCase();
            LoginPassword = jPasswordField1.getText().trim();
            LoginUrlConnectionM3 = "https://bkrmvxm3.bangkokranch.com:21008/mne/servlet/MvxMCSvt"; //PRD
//            LoginUrlConnectionM3 = "https://bkrmvxm3.bangkokranch.com:22008/mne/servlet/MvxMCSvt"; //TST

            UserM3 = "MVXSECOFR";
            PasswordM3 = "lawson@90";

            LoginAppServer = "192.200.9.190";
            LoginAppPort = 16105;
            conn = ConnectDB2.LoginDB(LoginUsername, LoginPassword);
            if (conn.isClosed() != true) {

                this.setVisible(false);
                this.setTitle("Login For " + lblCompanyName.getText());
                String[] cmbtexxxx = CmbCompany.getSelectedItem().toString().split(":");
                LoginCono = cmbtexxxx[1];
                LoginDivision = cmbtexxxx[2];
                LoginCompanyName = cmbtexxxx[0];
                //PRODUCT
                Table_fin_caadd = "brldta0100.FIN_CASHADALL";
                Table_fin_sead = "brldta0100.FIN_SETTADALL";
                Table_fin_cact = "brldta0100.FIN_CACTBRALL";
                dbname = "BRLDTA0100";
                dbM3Name = "M3FDBPRD";

                //TESTING
//                Table_fin_caadd = "BRLDTABK01.FIN_CASHADALL";
//                Table_fin_sead = "BRLDTABK01.FIN_SETTADALL";
//                Table_fin_cact = "BRLDTABK01.FIN_CACTBRALL";
//                dbname = "BRLDTABK01";
//                dbM3Name = "M3FDBTST";

//                String program = "Account";
                String program = "Request";
//                String program = "dev";
                if (program.equalsIgnoreCase("Account")) {
                    new ShowCashAdvanceAcc().setVisible(true);
                } else if (program.equalsIgnoreCase("Request")) {
                    new ShowCashAdvanceRequester2().setVisible(true);
                } else {
                    new ShowCashAdvanceRequester2().setVisible(true);
                    new ShowCashAdvanceAcc().setVisible(true);
                }
            }

            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ErrorLogs);
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void CmbCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbCompanyActionPerformed

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // TODO add your handling code here:
        txtUsername.setText("m3srvict");
        jPasswordField1.setText("ict12345");
    }//GEN-LAST:event_label1MouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void label1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_label1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_label1ComponentHidden

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

        // TODO add your handling code here:
        Connection conn;
        try {
            LoginUsername = txtUsername.getText().trim().toUpperCase();
            LoginPassword = jPasswordField1.getText().trim();

            conn = ConnectDB2.LoginDB(LoginUsername, LoginPassword);
            if (conn.isClosed() != true) {
                this.setVisible(false);
                this.setTitle("Login For " + lblCompanyName.getText());
                String[] cmbtexxxx = CmbCompany.getSelectedItem().toString().split(":");
                LoginCono = cmbtexxxx[1];
                LoginDivision = cmbtexxxx[2];
                LoginCompanyName = cmbtexxxx[0];

//                String[] strFAC = Cmbfac.getSelectedItem().toString().split(" : ");
//                LoginFacility   = strFAC[0].trim();
                new ShowCashAdvanceRequester2().setVisible(true);
                //new Reportpur002().setVisible(true);

            }

            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());

        }
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("\\\\192.200.9.182\\movex\\AddOn_M3\\Source\\CashAdvance_MultiCompany\\dist\\คู่มือ_CSHADV.pdf");
                Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
                // no application registered for PDFs
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    public void GetCompanyResultData() throws Exception {

        Connection conn = ConnectDB2.ConnectionDB();
        Statement sta = conn.createStatement();

        String Sql1 = "SELECT TRIM(CCROW3) || ':' || trim(CCCONO) || ':' || trim(CCDIVI)  AS company\n"
                + "FROM M3FDBPRD.CMNDIV\n"
                + "WHERE CCDIVI NOT IN ('','120','130')\n"
                + "AND CCCONO NOT IN ('400', '700')\n"
                + "ORDER BY CCCONO ASC 	";

        rsCompany = sta.executeQuery(Sql1);

        while (rsCompany.next()) {
            String c = rsCompany.getString("company").trim();
            CmbCompany.addItem(c);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbCompany;
    private java.awt.Button btncancel;
    private java.awt.Button btnlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label lblCompanyName;
    private java.awt.TextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
