/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashadvance_multicompany;

import static cashadvance_multicompany.CashAdvanRequest.cmbSupplierADV;
import static cashadvance_multicompany.CashAdvanRequest.cmb_IT1GP;
import static cashadvance_multicompany.CashAdvanRequest.cmbcostcenter;
////import static cashadvance_multicompany.CashAdvanRequest.txtname;
////import static cashadvance_multicompany.CashAdvanRequest.txtsupline;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static cashadvance_multicompany.CashAdvanRequest.cmbstaffcode;
import static cashadvance_multicompany.CashAdvanRequest.txtaccname;
import static cashadvance_multicompany.CashAdvanRequest.txtaccno;
import static cashadvance_multicompany.CashAdvanRequest.txtbranch;

import java.sql.SQLException;
//import static PUR_SRN.CashAdvanRequesterExtra.txtnameextra;
//import static PUR_SRN.CashAdvanRequesterExtra.txtstaffex;
//import static PUR_SRN.CashAdvanRequesterExtra.txtsuplineextra;
//import static PUR_SRN.GrnForm.cmbSupplierGRN;
//import static PUR_SRN.PurchaseSrForm.cmbstaffcodepur;
//import static PUR_SRN.SrnForm.cmbstaffcode1;
//import static PUR_SRN.SrnFormExtra.cmbstaffcode2;

/**
 *
 * @author Monthon
 */
public class frmsearchCostCenter extends javax.swing.JFrame {

    public static DefaultTableModel model;
    public static String ProgramStep = "";

    /**
     * Creates new form frmsearch
     */
    public frmsearchCostCenter() {
        initComponents();
        GetCostcenterData();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSearch = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        btnSearchsupp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSearch);
        if (jTableSearch.getColumnModel().getColumnCount() > 0) {
            jTableSearch.getColumnModel().getColumn(0).setMinWidth(50);
            jTableSearch.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 480, 260);
        getContentPane().add(txtsearch);
        txtsearch.setBounds(130, 60, 229, 31);

        btnSearchsupp.setText("Search");
        btnSearchsupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchsuppActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchsupp);
        btnSearchsupp.setBounds(370, 60, 90, 31);

        jLabel1.setText("Costcenter :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 80, 31);

        setSize(new java.awt.Dimension(582, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchsuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchsuppActionPerformed

        GetCostCenter(txtsearch.getText().trim());
    }//GEN-LAST:event_btnSearchsuppActionPerformed

    private void jTableSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSearchMouseClicked
        // get the model from the jtable

        if (ProgramStep.equals("SearchCC")) {

            DefaultTableModel model = (DefaultTableModel) jTableSearch.getModel();

            // get the selected row index
            int selectedRowIndex = jTableSearch.getSelectedRow();

            // set the selected row data into jtextfields
            String C = (model.getValueAt(selectedRowIndex, 0).toString());
            String N = (model.getValueAt(selectedRowIndex, 1).toString());
            cmbcostcenter.setText(C + " : " + N);

            dispose();
        }


    }//GEN-LAST:event_jTableSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmsearchCostCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmsearchCostCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmsearchCostCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmsearchCostCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmsearchCostCenter().setVisible(true);
            }
        });
    }
//

    public void GetCostCenter(String searchlike) {

        SetModel();
        Classgetdata cgr = new Classgetdata();
        ResultSet rs1 = cgr.GetCostCenterResultwithsearchData(searchlike);

        try {
            while (rs1.next()) {

                model.insertRow(model.getRowCount(), new Object[]{
                    rs1.getString("eaaitm").trim(), rs1.getString("eatx40").trim()

                });

            }
        } catch (Exception e) {
        }

    }

    public void GetCostcenterData() {

        SetModel();
        Classgetdata cgr = new Classgetdata();
        ResultSet rs1 = cgr.GetCostcenterResultData();

        try {
            while (rs1.next()) {

                model.insertRow(model.getRowCount(), new Object[]{
                    rs1.getString("eaaitm").trim(), rs1.getString("eatx40").trim()

                });

            }
        } catch (Exception e) {
        }

    }

    private void SetModel() {

        try {
            model = (DefaultTableModel) jTableSearch.getModel();
            while (model.getRowCount() > 0) {
                for (int i = 0; i < model.getRowCount(); ++i) {
                    model.removeRow(i);

                }
            }

        } catch (Exception ex) {
            // Logger.getLogger(viewdata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnSearchsupp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableSearch;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
