/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashadvance_multicompany;

import static cashadvance_multicompany.CashAdvanRequest.txtAdvanceNo;
import static cashadvance_multicompany.frmLogin.LoginCompanyName;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jilasak
 */
public class frmWHTAX extends javax.swing.JFrame {
    
    DefaultTableModel model;

    /**
     * Creates new form frmWHTAX
     */
    public frmWHTAX() {
        initComponents();
        this.setTitle("Cash Advance Request For : " + LoginCompanyName);
        model = (DefaultTableModel) griddetail.getModel();
        try {
            txtAdvanceNo1.setText(txtAdvanceNo.getText().trim());
            SetFormDataWithSTEP1_Cash(txtAdvanceNo1.getText().trim());
            Get_DetailGrid(txtAdvanceNo1.getText().trim());
            
        } catch (Exception e) {
            System.out.println("Step 1 : FrmWHTAX");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        griddetail = new javax.swing.JTable();
        btnsave1 = new javax.swing.JButton();
        btnaddline = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtamtbfvat1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtvat1 = new javax.swing.JTextField();
        txtamt1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        txtamount1 = new javax.swing.JTextField();
        cmb_IT1GP_1 = new java.awt.TextField();
        jLabel12 = new javax.swing.JLabel();
        txtAdvanceNo1 = new java.awt.TextField();
        radiotaxchec_1 = new javax.swing.JRadioButton();
        radiofrontwork_1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Adv. Amount");

        griddetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice", "Supplier", "Name", "Invoice Date", "Desc", "Cost", "Amt", "VatC", "Vat Amt", "Expense", "Total Amt", "ShareService", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        griddetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                griddetailMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                griddetailMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(griddetail);

        btnsave1.setText("Save");
        btnsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave1ActionPerformed(evt);
            }
        });

        btnaddline.setBackground(new java.awt.Color(204, 255, 204));
        btnaddline.setText("Add Line");
        btnaddline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddlineActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Expenses Group");

        jLabel27.setText("จำนวนเงินก่อน Vat7%");

        txtamtbfvat1.setEditable(false);
        txtamtbfvat1.setBackground(new java.awt.Color(255, 255, 204));
        txtamtbfvat1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtamtbfvat1.setText("0.00");

        jLabel31.setText("Vta 7%");

        txtvat1.setEditable(false);
        txtvat1.setBackground(new java.awt.Color(255, 255, 204));
        txtvat1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvat1.setText("0.00");

        txtamt1.setEditable(false);
        txtamt1.setBackground(new java.awt.Color(255, 255, 204));
        txtamt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtamt1.setText("0.00");

        jLabel32.setText("Total Amount");

        jLabel35.setText("Balance");

        txtbalance.setEditable(false);
        txtbalance.setBackground(new java.awt.Color(255, 255, 204));
        txtbalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtbalance.setText("0.00");

        txtamount1.setEditable(false);
        txtamount1.setBackground(new java.awt.Color(255, 255, 204));
        txtamount1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtamount1.setText("0.00");

        cmb_IT1GP_1.setBackground(new java.awt.Color(204, 255, 255));
        cmb_IT1GP_1.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Advance No.");

        txtAdvanceNo1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdvanceNo1.setEditable(false);

        radiotaxchec_1.setForeground(new java.awt.Color(255, 0, 51));
        radiotaxchec_1.setText(" หักหน้าเช็ค");
        radiotaxchec_1.setEnabled(false);

        radiofrontwork_1.setForeground(new java.awt.Color(255, 0, 0));
        radiofrontwork_1.setText(" หักหน้างาน");
        radiofrontwork_1.setEnabled(false);

        jLabel1.setText("WH TAX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnaddline, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txtvat1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(310, 310, 310)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txtamt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txtamtbfvat1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtAdvanceNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)
                                                .addComponent(txtamount1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(cmb_IT1GP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiotaxchec_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radiofrontwork_1))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(btnsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtAdvanceNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtamount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_IT1GP_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtamtbfvat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(radiotaxchec_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(radiofrontwork_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtvat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtamt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnaddline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1082, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SetFormDataWithSTEP1_Cash(String CASH_CANO_) {
        Classgetdata cgd = new Classgetdata();
        ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();
        ResultSet rs = cgd.GetDataCashAdvanRequest_HeaderResultData(CASH_CANO_);
        try {
            String WHTAX = "";
            while (rs.next()) {
                txtamount1.setText(rs.getString("CASH_AMT"));
                cmb_IT1GP_1.setText(cgd.GetExpensSubGroupDescWithCode(rs.getString("CASH_EXPG")));
                WHTAX = rs.getString("CASH_WHTAX").trim();
            }
            if (WHTAX.equalsIgnoreCase("1")) {
                radiotaxchec_1.setSelected(true);
            }
            rs.close();
            Get_DetailGrid(CASH_CANO_);
        } catch (SQLException ex) {
            Logger.getLogger(frmWHTAX.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void griddetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_griddetailMouseClicked
        ClassSetdata csr = new ClassSetdata();
        String frmWHTAX = "frmWHTAX";
        csr.DeleLine(frmWHTAX);
        Get_DetailGrid(txtAdvanceNo1.getText().trim());
        
        Cal_AmountSettlementWithOutGrid();
    }//GEN-LAST:event_griddetailMouseClicked

    private void griddetailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_griddetailMouseReleased
        // TODO add your handling code here:
        SetCalculateDetailModel();
    }//GEN-LAST:event_griddetailMouseReleased

    private void btnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave1ActionPerformed
        // TODO add your handling code here:

        String statussetdata;
        ClassSetdata setdata = new ClassSetdata();
        ClassCheckDataProgram cdp = new ClassCheckDataProgram();
        
        String CASH_CANO = txtAdvanceNo1.getText().trim();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would You Like to Save Cash Advance ?", "Warning",
                dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            
            String WHTAXTYPE = "";
            String CASH_REAMT = "0.00";
            String CASH_RETOBANK = "";
            
            model = (DefaultTableModel) griddetail.getModel();
            if (!CASH_CANO.isEmpty()) {
                CASH_CANO = setdata.SaveCashAdvanceWHTAX(CASH_CANO, model, WHTAXTYPE, CASH_REAMT, CASH_RETOBANK);
                dispose();
            }
            
        }

    }//GEN-LAST:event_btnsave1ActionPerformed

    private void btnaddlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddlineActionPerformed
        new frmAddLineInvStep1().setVisible(true);
    }//GEN-LAST:event_btnaddlineActionPerformed
    private void msbox(String strr) {
        int dialogButton = JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(null, strr, "Warning", dialogButton);
    }
    
    private void Get_DetailGrid(String CashAdvanceNo) {
        
        Classgetdata cgd = new Classgetdata();
        ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();
        ResultSet rs = cgd.GetDataAdvanceDetailResultData(CashAdvanceNo);
        try {
            //    SetModel();
            model = (DefaultTableModel) griddetail.getModel();
            int iiii = 0;
            
            Double amt = 0.00;
            Double vat = 0.00;
            Double amtBeforeVat = 0.00;
            Double Sum = 0.00;
            Double Advamt = Double.parseDouble(txtamount1.getText().trim());
            while (rs.next()) {
                //  String Nassme= cgd.GetItemName_MitMas(rs.getString("EPRL_ITNO").trim());
                model.setValueAt(rs.getString("SETT_INVC").trim(), iiii, 0);
                model.setValueAt(rs.getString("SETT_SUPP").trim(), iiii, 1);
                model.setValueAt(cgd.Get_SupplierNameWithCode2(rs.getString("SETT_SUPP").trim()), iiii, 2);
                model.setValueAt(checkdataprogram.GetDateFormatSetShowString(checkdataprogram.GetDecmalTodate(rs.getInt("SETT_INVD"))), iiii, 3);
                
                model.setValueAt(rs.getString("SETT_DESC").trim(), iiii, 4);
                model.setValueAt(rs.getString("SETT_COST").trim(), iiii, 5);
                
                model.setValueAt(rs.getDouble("SETT_AMTB"), iiii, 6);
                model.setValueAt(rs.getDouble("SETT_VATC"), iiii, 7);
                model.setValueAt(rs.getDouble("SETT_VATA"), iiii, 8);
                model.setValueAt(rs.getString("SETT_NODES"), iiii, 9);
                model.setValueAt(rs.getDouble("SETT_AMTT"), iiii, 10);
                model.setValueAt(rs.getString("SETT_BRAC"), iiii, 11);
                amt += rs.getDouble("SETT_AMTT");
                vat += rs.getDouble("SETT_VATA");
                amtBeforeVat += rs.getDouble("SETT_AMTB");
                iiii++;
                
            }
            
            amtBeforeVat = checkdataprogram.Double2digitReturn(amtBeforeVat);
            amt = checkdataprogram.Double2digitReturn(amt);
            vat = checkdataprogram.Double2digitReturn(vat);
            Cal_AmountSettlementWithGrid(Advamt, amtBeforeVat, vat, amt);
            
            rs.close();
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    }
    
    private void Cal_AmountSettlementWithGrid(Double Advamt, Double AmtBfVat, Double AmtVat, Double TotalAmt) {
        ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();
        Double Sum = 0.00;
        
        txtamtbfvat1.setText(String.valueOf(AmtBfVat).trim());
        txtvat1.setText(String.valueOf(AmtVat).trim());
        txtamt1.setText(String.valueOf(AmtBfVat+AmtVat).trim());
        
        Double balance = 0.00;
        Sum = Advamt - (AmtBfVat + AmtVat);
        Sum = checkdataprogram.Double2digitReturn(Sum);
        txtbalance.setText(String.valueOf(Sum).trim());
        
    }
    
    private void Cal_AmountSettlementWithOutGrid() {
        ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();
        Double Advamt = Double.parseDouble(txtamount1.getText().trim());
        Double AmtBfVat = Double.parseDouble(txtamtbfvat1.getText().trim());
        Double AmtVat = Double.parseDouble(txtvat1.getText().trim());
        Double TotalAmt = Double.parseDouble(txtamt1.getText().trim());
        
        Double Sum = 0.00;
        txtbalance.setText("0.00");
//        txtrefund1.setText("0.00");
        Sum = Advamt - (AmtBfVat + AmtVat);
        Sum = checkdataprogram.Double2digitReturn(Sum);
        txtbalance.setText(String.valueOf(Sum));
        
    }
    
    private void Set_RdoSettlement(boolean Status) {
//        rdoReturnSCB.setEnabled(Status);
//        rdoReturnKBANK.setEnabled(Status);
//        rdoPTC.setEnabled(Status);
//        rdoTransBank.setEnabled(Status);
//        rdoPTC.setSelected(Status);
//        rdoReturnSCB.setSelected(Status);
//        rdoReturnKBANK.setSelected(Status);
//        rdoPTC.setSelected(Status);
//        rdoTransBank.setSelected(Status);
    }
    
    private void SetCalculateDetailModel() {
        
        double TotalAmountAllReturn = 0;
        double TotalAmountReturn = 0;
        double TotalVatAmountReturn = 0;
        Classgetdata getdataDatabase = new Classgetdata();
        ClassCheckDataProgram Classcheck = new ClassCheckDataProgram();
        
        try {
            Date s;
            for (int i = 0; i < model.getRowCount(); ++i) {

                ////////////////////////////////////////DELETE.........................,,,,,,,,,,,,,,,,
                boolean chkdelete = false;
                
                try {
                    chkdelete = (boolean) model.getValueAt(i, 10);
                } catch (Exception e) {
                    chkdelete = false;
                }
                
                if (chkdelete) {  // FUNTION TO PRINT REPORT
                    ClassSetdata csr = new ClassSetdata();
                    String frmWHTAX = "frmWHTAX";
                    csr.DeleLine(frmWHTAX);
                    // cgr.
                    // model.removeRow(i);

                }
            }
        } catch (Exception e) {
            // System.out.println(e.toString());
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmWHTAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmWHTAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmWHTAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmWHTAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmWHTAX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddline;
    private javax.swing.JButton btnsave1;
    public static java.awt.TextField cmb_IT1GP_1;
    public static javax.swing.JTable griddetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JRadioButton radiofrontwork_1;
    public static javax.swing.JRadioButton radiotaxchec_1;
    public static java.awt.TextField txtAdvanceNo1;
    public static javax.swing.JTextField txtamount1;
    public static javax.swing.JTextField txtamt1;
    public static javax.swing.JTextField txtamtbfvat1;
    public static javax.swing.JTextField txtbalance;
    public static javax.swing.JTextField txtvat1;
    // End of variables declaration//GEN-END:variables
}
