/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashadvance_multicompany;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author Jilasak
 */
public class ShowCashAdvanceAccRP extends javax.swing.JFrame {

    /**
     * Creates new form ShowCashAdvanceAccRP
     */
    public ShowCashAdvanceAccRP() {
        initComponents();
        this.setTitle("Cash Advance Accounting Report");
        txt_Fromdate.setEnabled(false);
        txt_Todate.setEnabled(false);
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Todate = new org.jdesktop.swingx.JXDatePicker();
        txt_Fromdate = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        RequestDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestDatePicker1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PUR_SRN/icon.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 100, 100);

        jLabel3.setText("From :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 60, 40, 40);

        jLabel4.setText("To :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 60, 30, 40);

        txt_Todate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TodateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Todate);
        txt_Todate.setBounds(420, 60, 180, 40);

        txt_Fromdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FromdateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Fromdate);
        txt_Fromdate.setBounds(200, 60, 180, 40);

        jButton1.setText("Print Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 120, 180, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash Advance Voucher", "Cash Advance Settlement" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(200, 10, 180, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Report Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 10, 90, 30);

        jButton2.setText("Export to excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 120, 180, 40);

        setSize(new java.awt.Dimension(633, 240));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TodateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TodateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TodateActionPerformed

    private void RequestDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestDatePicker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestDatePicker1ActionPerformed

    private void txt_FromdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FromdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FromdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        ClassgetReport cgr = new ClassgetReport();
//
//        String fromdate = GetDateFormatSet(txt_Fromdate.getDate());
//        String todate = GetDateFormatSet(txt_Todate.getDate());
//        if (jComboBox1.getSelectedItem() == "Cash Advance Voucher") {
//            cgr.getReportADV3();
//        }
//        if (jComboBox1.getSelectedItem() == "Cash Advance Settlement") {
//            cgr.getReportADV1_FromToDate(fromdate, todate);
//        }


    }//GEN-LAST:event_jButton1ActionPerformed
    public String GetDateFormatSet(Date dateToset) {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat format1 = new SimpleDateFormat("yyyyMMdd", Locale.ENGLISH);
        String formatted = format1.format(dateToset);
        return formatted;
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem() == "Cash Advance Voucher") {
            txt_Fromdate.setEnabled(false);
            txt_Todate.setEnabled(false);
            jButton1.setEnabled(false);
        } else {
            txt_Fromdate.setEnabled(true);
            txt_Todate.setEnabled(true);
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        ClassgetReport cgr = new ClassgetReport();
//
//        String fromdate = "";
//        String todate = "";
//        if (jComboBox1.getSelectedItem() == "Cash Advance Voucher") {
//            cgr.getReportADV3_xls();
//        }
//        if (jComboBox1.getSelectedItem() == "Cash Advance Settlement") {
//            fromdate = GetDateFormatSet(txt_Fromdate.getDate());
//            todate = GetDateFormatSet(txt_Todate.getDate());
//            cgr.getReportADV1_FromToDate_XLS(fromdate, todate);
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAccRP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAccRP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAccRP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAccRP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCashAdvanceAccRP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.jdesktop.swingx.JXDatePicker RequestDatePicker1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static org.jdesktop.swingx.JXDatePicker txt_Fromdate;
    public static org.jdesktop.swingx.JXDatePicker txt_Todate;
    // End of variables declaration//GEN-END:variables
}
