/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashadvance_multicompany;

import static cashadvance_multicompany.frmLogin.LoginCompanyName;
import static cashadvance_multicompany.frmLogin.LoginUsername;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jilasak
 */
public class ShowCashAdvanceAcc extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form ShowCashAdvanceAcc
     */
    public ShowCashAdvanceAcc() {

        initComponents();
        Locale.setDefault(Locale.US);
        Date d = new Date();
        SimpleDateFormat A = new SimpleDateFormat("yyyyMMdd");
        txtReceivedate.setText(A.format(d));

        try {
            txtReceivedate.setEnabled(true);
//            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));

            lblCompanyName.setText("Company Name : " + LoginCompanyName);
            this.setTitle("Cash Advance Accounting For " + lblCompanyName.getText());

            SetNewFormShowCashAdvance();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnEditPr1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GridShowServiceRequestNo = new javax.swing.JTable();
        txtReceivedate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblCompanyName = new java.awt.Label();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Cash Advance Accounting");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 131, 300, 22);

        btnEditPr1.setText("Edit Cash Accounting");
        btnEditPr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPr1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPr1);
        btnEditPr1.setBounds(10, 161, 170, 40);

        GridShowServiceRequestNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GridShowServiceRequestNo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Advance No.", "Payment Remark", "User Request", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GridShowServiceRequestNo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 211, 740, 304);

        txtReceivedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceivedateActionPerformed(evt);
            }
        });
        getContentPane().add(txtReceivedate);
        txtReceivedate.setBounds(420, 130, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText(" Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 130, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Report Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 100, 80, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash Advance Settlement" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(420, 100, 200, 20);

        jButton2.setText("Report View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 110, 120, 50);

        jButton1.setText("Refresh Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 181, 120, 29);

        lblCompanyName.setAlignment(java.awt.Label.CENTER);
        lblCompanyName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCompanyName.setText("Company Name");
        getContentPane().add(lblCompanyName);
        lblCompanyName.setBounds(110, 20, 580, 28);

        jButton3.setText("Re print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 180, 90, 29);

        setSize(new java.awt.Dimension(786, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditPr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPr1ActionPerformed
        CashAdvanAccounting.CashAdvanceRequestNo = String.valueOf(model.getValueAt(GridShowServiceRequestNo.getSelectedRow(), 0));
        CashAdvanAccounting newform = new CashAdvanAccounting();
        newform.setDefaultCloseOperation(CashAdvanAccounting.DISPOSE_ON_CLOSE);
        newform.setVisible(true);
    }//GEN-LAST:event_btnEditPr1ActionPerformed

    private void txtReceivedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceivedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceivedateActionPerformed

    private void SetModel() {
        model = (DefaultTableModel) GridShowServiceRequestNo.getModel();
        try {
            while (model.getRowCount() > 0) {
                for (int i = 0; i < model.getRowCount(); ++i) {
                    model.removeRow(i);
                }
            }
        } catch (Exception ex) {
            System.out.print(ex);
        }
    }

    private void SetNewFormShowCashAdvance() {

        try {

            lblCompanyName.setText("Company Name : " + LoginCompanyName);
            this.setTitle("Show Cash Advance Accounting For " + lblCompanyName.getText());

            Classgetdata cgd = new Classgetdata();
            ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();

            ResultSet rs = cgd.Get_CashAccountingUserListUserResultData(LoginUsername);
            SetModel();
            while (rs.next()) {

                String Stat = rs.getString("CASH_STAT").trim();

                String StatusName = "";
                switch (Stat) {
                    case "20":
                        StatusName = "Submit Step 1";
                        break;
                    case "30":
                        StatusName = "Submit Step 2";
                        break;
                    case "45":
                        StatusName = "Submit Step 3";
                        break;
                    case "50":
                        StatusName = "Submit Step 4";
                        break;
                    case "99":
                        StatusName = "Cancel";
                        break;

                }

                String str = rs.getString("CASH_PPS1").trim();
                String[] arr = str.split("u");
                String text = rs.getString("CASH_PPS1").trim();
                for (int i = 1; i < arr.length; i++) {
                    // int hexVal = Integer.parseInt(arr[i], 16);
                    //  text +=  hexVal;
                }

                model.insertRow(model.getRowCount(), new Object[]{
                    rs.getString("CASH_CANO").trim(), rs.getString("CASH_PPS1").trim(),
                    rs.getString("CASH_REQB").trim(), StatusName
                });
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //        if (jComboBox1.getSelectedItem() == "Received Advance Entry") {
        //            txtReceivedate.setEnabled(true);
        //        } else {
        //            txtReceivedate.setEnabled(false);
        //        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        ClassgetReport cgr = new ClassgetReport();
        if (jComboBox1.getSelectedItem() == "Cash Advance Settlement") {
            cgr.getReportADV1();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SetNewFormShowCashAdvance();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ClassgetReport cgr = new ClassgetReport();
        ClassCheckDataProgram cdp = new ClassCheckDataProgram();
        String CASH_STDA = txtReceivedate.getText();
        cgr.getReportACC_1(CASH_STDA, CASH_STDA);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCashAdvanceAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GridShowServiceRequestNo;
    private javax.swing.JButton btnEditPr1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lblCompanyName;
    public static javax.swing.JTextField txtReceivedate;
    // End of variables declaration//GEN-END:variables
}
