/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashadvance_multicompany;

import static cashadvance_multicompany.frmLogin.LoginCompanyName;
import static cashadvance_multicompany.frmLogin.LoginUsername;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;
/**
 *
 * @author Jilasak
 */
public class ShowCashAdvanceRequester2 extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form test
     */
    public ShowCashAdvanceRequester2() {
        initComponents();
        lblCompanyName.setText("Company Name : " + LoginCompanyName);
        this.setTitle("Cash Advance Requestor For " + lblCompanyName.getText());
        SetNewFormShowCashAdvance();
    }

    private void SetModel() {
        model = (DefaultTableModel) GridShowServiceRequestNo.getModel();
        try {
            while (model.getRowCount() > 0) {
                for (int i = 0; i < model.getRowCount(); ++i) {
                    model.removeRow(i);
                }
            }
        } catch (Exception ex) {
            System.out.print(ex);
        }
    }

    private void SetNewFormShowCashAdvance() {

        try {

            Classgetdata cgd = new Classgetdata();
            ClassCheckDataProgram checkdataprogram = new ClassCheckDataProgram();

            ResultSet rs = cgd.Get_CashRequestUserListUserResultData(LoginUsername);
            SetModel();
            while (rs.next()) {

                String Stat = rs.getString("CASH_STAT").trim();

                String StatusName = "";
                switch (Stat) {
                    case "10":
                        StatusName = "Normal";
                        break;
                    case "40":
                        StatusName = "Submit Step3";
                        break;
                    case "99":
                        StatusName = "Cancel";
                        break;

                }

                model.insertRow(model.getRowCount(), new Object[]{
                    rs.getString("CASH_CANO").trim(), rs.getString("CASH_PPS1").trim(),
                    rs.getString("CASH_REQB").trim(), StatusName
                });
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyName = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        btnAddnewPr = new javax.swing.JButton();
        btnEditPr = new javax.swing.JButton();
        btnReportSrn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GridShowServiceRequestNo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyName.setAlignment(java.awt.Label.CENTER);
        lblCompanyName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCompanyName.setText("Company Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Cash Advance Requestor");

        btnAddnewPr.setText("Add New Cash Requester");
        btnAddnewPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnewPrActionPerformed(evt);
            }
        });

        btnEditPr.setText("Edit Cash Requestor");
        btnEditPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPrActionPerformed(evt);
            }
        });

        btnReportSrn.setText("Report Cash Requestor");
        btnReportSrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportSrnActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GridShowServiceRequestNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GridShowServiceRequestNo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Advance No.", "Payment Remark", "User Request", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GridShowServiceRequestNo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblCompanyName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 513, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnAddnewPr, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnEditPr, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnReportSrn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditPr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReportSrn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddnewPr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddnewPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnewPrActionPerformed
        // TODO add your handling scode here:
        CashAdvanRequest.CashAdvanceRequestNo = "";
        CashAdvanRequest car = new CashAdvanRequest();
        car.setDefaultCloseOperation(CashAdvanRequest.DISPOSE_ON_CLOSE);
        car.setVisible(true);

    }//GEN-LAST:event_btnAddnewPrActionPerformed

    private void btnEditPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPrActionPerformed
        CashAdvanRequest.CashAdvanceRequestNo = String.valueOf(model.getValueAt(GridShowServiceRequestNo.getSelectedRow(), 0));
        CashAdvanRequest newform = new CashAdvanRequest();
        newform.setDefaultCloseOperation(CashAdvanRequest.DISPOSE_ON_CLOSE);
        newform.setVisible(true);

    }//GEN-LAST:event_btnEditPrActionPerformed

    private void btnReportSrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportSrnActionPerformed
        // TODO add your handling code here:
        //        String PrNo = String.valueOf(model.getValueAt(GridShowServiceRequestNo.getSelectedRow(), 0));
        //        ClassgetReport cgr = new ClassgetReport();
        //        cgr.getReportAdvReq1(PrNo);

        CashAdvanAccounting cag = new CashAdvanAccounting();
        cag.setDefaultCloseOperation(CashAdvanRequest.DISPOSE_ON_CLOSE);
        cag.setVisible(true);
    }//GEN-LAST:event_btnReportSrnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SetNewFormShowCashAdvance();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceRequester2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceRequester2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceRequester2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCashAdvanceRequester2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCashAdvanceRequester2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GridShowServiceRequestNo;
    private javax.swing.JButton btnAddnewPr;
    private javax.swing.JButton btnEditPr;
    private javax.swing.JButton btnReportSrn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lblCompanyName;
    // End of variables declaration//GEN-END:variables
}
